import type { Recipe } from "./types";

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Pasta al pomodoro",
    description: "Un classico italiano semplice e veloce, perfetto per una cena in famiglia.",
    ingredients: "Spaghetti 400g, pomodori pelati 400g, aglio, basilico, olio, sale, pepe",
    instructions: "Cuocere la pasta in acqua salata. In una padella soffriggere aglio e aggiungere i pomodori. Scolare la pasta e saltarla in padella con il sugo. Servire con basilico fresco.",
    author: "Maria R.",
    created_at: "2025-02-01T12:00:00Z",
  },
  {
    id: "2",
    title: "Torta di mele",
    description: "Dolce della nonna, morbido e profumato.",
    ingredients: "Mele 4, farina 300g, zucchero 150g, uova 2, burro 100g, lievito, cannella",
    instructions: "Impastare farina, zucchero, uova e burro. Aggiungere le mele a fette e il lievito. Infornare a 180°C per 40 minuti.",
    author: "Giuseppe B.",
    created_at: "2025-02-05T10:30:00Z",
  },
  {
    id: "3",
    title: "Insalata di quinoa",
    description: "Piatto unico leggero, ideale per pranzo o cena estiva.",
    ingredients: "Quinoa 200g, cetriolo, pomodorini, feta, olive, olio, limone, prezzemolo",
    instructions: "Cuocere la quinoa e lasciarla raffreddare. Tagliare verdure e feta a cubetti. Mescolare con olio, limone e prezzemolo.",
    author: "Laura M.",
    created_at: "2025-02-08T09:15:00Z",
  },
  {
    id: "4",
    title: "Risotto ai funghi",
    description: "Risotto cremoso con funghi porcini, piatto perfetto per l'autunno.",
    ingredients: "Riso Arborio 320g, funghi porcini 300g, scalogno, brodo vegetale, burro, parmigiano, prezzemolo",
    instructions: "Soffriggere lo scalogno. Tostare il riso, sfumare con vino bianco. Aggiungere i funghi e il brodo poco alla volta. Mantecare con burro e parmigiano.",
    author: "Marco T.",
    created_at: "2025-02-06T14:00:00Z",
  },
  {
    id: "5",
    title: "Tiramisù",
    description: "Dolce al cucchiaio senza cottura, con mascarpone e caffè.",
    ingredients: "Savoiardi 300g, mascarpone 500g, uova 4, zucchero 100g, caffè forte, cacao amaro",
    instructions: "Preparare il caffè e lasciarlo intiepidire. Montare tuorli con zucchero, unire il mascarpone e poi gli albumi montati. Stratificare savoiardi inzuppati e crema. Spolverizzare con cacao.",
    author: "Elena F.",
    created_at: "2025-02-07T11:20:00Z",
  },
  {
    id: "6",
    title: "Pollo al limone",
    description: "Secondo leggero e aromatico, ideale con insalata o verdure grigliate.",
    ingredients: "Petto di pollo 2, limoni 2, aglio, rosmarino, olio, sale, pepe",
    instructions: "Rosolare il pollo in padella. Aggiungere aglio e rosmarino, sfumare con succo di limone. Cuocere a fuoco medio fino a doratura. Servire con fette di limone.",
    author: "Andrea S.",
    created_at: "2025-02-09T08:45:00Z",
  },
  {
    id: "7",
    title: "Lasagne alla bolognese",
    description: "Piatto della domenica: strati di pasta, ragù e besciamella.",
    ingredients: "Pasta per lasagne, ragù 800g, besciamella 500ml, parmigiano, noce moscata",
    instructions: "Alternare strati di pasta fresca, ragù e besciamella in una teglia. Finire con besciamella e parmigiano. Infornare a 180°C per 40 minuti fino a gratinatura.",
    author: "Paolo D.",
    created_at: "2025-02-04T18:00:00Z",
  },
  {
    id: "8",
    title: "Bruschetta al pomodoro",
    description: "Antipasto veloce: pane tostato, pomodoro fresco e basilico.",
    ingredients: "Pane casereccio 8 fette, pomodorini 400g, aglio, basilico, olio extravergine, sale",
    instructions: "Tostare il pane. Tagliare i pomodorini a cubetti e condire con aglio, basilico, olio e sale. Distribuire sul pane e servire subito.",
    author: "Chiara L.",
    created_at: "2025-02-03T12:30:00Z",
  },
  {
    id: "9",
    title: "Brownies al cioccolato",
    description: "Dolce americano morbidissimo, con cuore fondente.",
    ingredients: "Cioccolato fondente 200g, burro 150g, zucchero 200g, uova 3, farina 80g, cacao, noci",
    instructions: "Sciogliere cioccolato e burro a bagnomaria. Unire zucchero, uova, farina e cacao. Aggiungere noci. Infornare in stampo quadrato a 170°C per 25 minuti.",
    author: "Sara N.",
    created_at: "2025-02-02T16:45:00Z",
  },
];
